(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<ACPackages`


(* ::Subsection::Closed:: *)
(*\:041f\:043e\:0441\:0442\:0440\:043e\:0435\:043d\:0438\:0435 \:0441\:0438\:0441\:0442\:0435\:043c\:044b \:0438 \:043c\:0430\:0442\:0440\:0438\:0446*)


(* ::Subsubsection:: *)
(*(*\:041f\:043e\:043b\:0443\:0447\:0435\:043d\:0438\:0435 \:0443\:0440\:0430\:0432\:043d\:0435\:043d\:0438\:0439 \:0441\:043c.CurvSystCoor-pseudotor.nb*)*)
(*eqs\[Phi]r[\[Lambda]_,\[Omega]_,\[Epsilon]_,\[Kappa]_,m_,Re_]*)


(* ::Text::Closed:: *)
(*\:0440\:0430\:0437\:043b\:043e\:0436\:0435\:043d\:043d\:043e\:0435 \:043f\:043e \:043c\:043e\:0434\:0430\:043c (\:0441 1-\:0439 \:043d\:0435\:0432\:0435\:0440\:043d\:043e, \:0442.\:043a. \:043d\:0435\:0442 \:0437\:0430\:0446\:0435\:043f\:043b\:0435\:043d\:0438\:044f \:043c\:043e\:0434)*)


(* ::Input:: *)
(*eqs\[Phi]r[\[Lambda]_,\[Omega]_,\[Epsilon]_,\[Kappa]_,m_,Re_]:=Which[m==0,{Re \[Lambda] \[Rho] v\[Zeta][\[Rho]]-*)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]-\[Rho] *)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]],(-1+Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] ((1+Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]-\[Rho] (2 *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "3", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "4", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]]))},*)
(*m==1,{(1+Re \[Lambda] \[Rho]^2) v\[Zeta][\[Rho]]+\[Rho] (\[ImaginaryI] G Re \[Rho] \[Psi][\[Rho]]/2-( *)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] *)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]])),(-3+Re \[Lambda] \[Rho]^2) \[Psi][\[Rho]]+\[Rho] ((3-Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] (-(3+Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] (2 *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "3", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "4", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]])))},*)
(*True,{(m^2+Re \[Lambda] \[Rho]^2) v\[Zeta][\[Rho]]+\[Rho] (\[ImaginaryI] G m Re \[Rho] \[Psi][\[Rho]]/2-( *)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] *)
(*\!\(\*SuperscriptBox["v\[Zeta]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]])),(m^2 (-4+m^2+Re \[Lambda] \[Rho]^2) \[Psi][\[Rho]]+\[Rho] ((1+2 m^2-Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]-\[Rho] ((1+2 m^2+Re \[Lambda] \[Rho]^2) *)
(*\!\(\*SuperscriptBox["\[Psi]", "\[Prime]\[Prime]",*)
(*MultilineFunction->None]\)[\[Rho]]-\[Rho] (2 *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "3", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]]+\[Rho] *)
(*\!\(\*SuperscriptBox["\[Psi]", *)
(*TagBox[*)
(*RowBox[{"(", "4", ")"}],*)
(*Derivative],*)
(*MultilineFunction->None]\)[\[Rho]]))))}];*)


(* ::Text::Closed:: *)
(*\:0442\:0435\:043a\:0443\:0449\:0435\:0435: \:0441\:0438\:0441\:0442\:0435\:043c\:0430 \:0434\:043b\:044f \[Psi] \:0438 v\[Zeta], \:043e\:0431\:0440\:0435\:0437\:0430\:043d\:043d\:0430\:044f \:0434\:043e \[Kappa]^1*)
(*(eqs\[Phi]r[\[Lambda],\[Omega],\[Epsilon],\[Kappa],G,Re])*)


eqs\[Phi]r[\[Lambda]_,\[Omega]_,\[Epsilon]_,\[Kappa]_,G_,Rn_]:={1/(Rn \[Rho]) \[Kappa] (-1/2 G Rn \[Rho]^2 Sin[\[Phi]] \[Psi][\[Rho],\[Phi]]+Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1/4608G Rn^2 (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1/4 G Rn (-1+\[Rho]^2) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 Rn \[Omega] Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1/737280 G Rn (46080 (-1+3 \[Rho]^2)+G^2 Rn^2 (19-120 \[Rho]^2+150 \[Rho]^4-70 \[Rho]^6+9 \[Rho]^8)-40 G Rn^2 (-3+18 \[Rho]^2-20 \[Rho]^4+7 \[Rho]^6) \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-\[Rho] Cos[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-(G Rn^2 \[Rho] (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])/4608+1/4 G Rn \[Rho] (-1+\[Rho]^2) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 Rn \[Rho] \[Omega] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1/737280 G Rn \[Rho] (-1+\[Rho]^2) (46080+G^2 Rn^2 (-19+21 \[Rho]^2-9 \[Rho]^4+\[Rho]^6)-40 G Rn^2 (3-3 \[Rho]^2+\[Rho]^4) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])+\[Kappa]^2 ((Cos[\[Phi]]^2 v\[Zeta][\[Rho],\[Phi]])/Rn-(G Rn (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]]^2 v\[Zeta][\[Rho],\[Phi]])/4608+(Sin[\[Phi]]^2 v\[Zeta][\[Rho],\[Phi]])/Rn-(G Rn (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]]^2 v\[Zeta][\[Rho],\[Phi]])/4608+1/2 G \[Rho]^2 Cos[\[Phi]] Sin[\[Phi]] \[Psi][\[Rho],\[Phi]]-1/737280 G (-1+\[Rho]^2) (46080+G^2 Rn^2 (-19+21 \[Rho]^2-9 \[Rho]^4+\[Rho]^6)-40 G Rn^2 (3-3 \[Rho]^2+\[Rho]^4) \[Omega]) Cos[\[Phi]] Sin[\[Phi]] \[Psi][\[Rho],\[Phi]]+1/737280 G (46080 (-1+3 \[Rho]^2)+G^2 Rn^2 (19-120 \[Rho]^2+150 \[Rho]^4-70 \[Rho]^6+9 \[Rho]^8)-40 G Rn^2 (-3+18 \[Rho]^2-20 \[Rho]^4+7 \[Rho]^6) \[Omega]) Cos[\[Phi]] Sin[\[Phi]] \[Psi][\[Rho],\[Phi]]-(Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])/Rn+(G Rn (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])/4608-1/59454259200 G Rn (-1+\[Rho]^2) (G^3 Rn^2 (-4979+20521 \[Rho]^2-13499 \[Rho]^4+4421 \[Rho]^6-829 \[Rho]^8+35 \[Rho]^10)-116121600 (-1+3 \[Rho]^2) \[Omega]-16 G^2 Rn^2 (3111-11789 \[Rho]^2+5536 \[Rho]^4-1184 \[Rho]^6+216 \[Rho]^8) \[Omega]-6720 G (-7296+17 Rn^2 \[Omega]^2+5 Rn^2 \[Rho]^6 \[Omega]^2+\[Rho]^2 (26112-55 Rn^2 \[Omega]^2)+\[Rho]^4 (-8448+5 Rn^2 \[Omega]^2))) Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1/4 G (-1+\[Rho]^2) Cos[\[Phi]]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1/737280 G (-1+\[Rho]^2) (46080+G^2 Rn^2 (-19+21 \[Rho]^2-9 \[Rho]^4+\[Rho]^6)-40 G Rn^2 (3-3 \[Rho]^2+\[Rho]^4) \[Omega]) Cos[\[Phi]]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1/59929893273600 G (8820 (G^4 Rn^4 (-1+\[Rho]^2)^3 (76-103 \[Rho]^2+57 \[Rho]^4-13 \[Rho]^6+\[Rho]^8)-8 G^3 Rn^4 (-1+\[Rho]^2)^3 (-117+138 \[Rho]^2-62 \[Rho]^4+8 \[Rho]^6) \[Omega]+184320 G Rn^2 (-47+96 \[Rho]^2-66 \[Rho]^4+13 \[Rho]^6) \[Omega]-35389440 (-1+\[Rho]^2) (-30+Rn^2 (-1+\[Rho]^2) \[Omega]^2)+192 G^2 Rn^2 (5 Rn^2 \[Rho]^10 \[Omega]^2+60 \[Rho]^2 (76+Rn^2 \[Omega]^2)-6 \[Rho]^8 (52+5 Rn^2 \[Omega]^2)+15 \[Rho]^6 (128+5 Rn^2 \[Omega]^2)-3 (808+5 Rn^2 \[Omega]^2)-5 \[Rho]^4 (864+19 Rn^2 \[Omega]^2)))+(G^4 Rn^4 (-145690+771792 \[Rho]^2-1244565 \[Rho]^4+980784 \[Rho]^6-448350 \[Rho]^8+131544 \[Rho]^10-20727 \[Rho]^12+1280 \[Rho]^14)-325140480 G Rn^2 (-101+380 \[Rho]^2-330 \[Rho]^4+84 \[Rho]^6) \[Omega]-252 G^3 Rn^4 (6017-31504 \[Rho]^2+49530 \[Rho]^4-36960 \[Rho]^6+15050 \[Rho]^8-3552 \[Rho]^10+329 \[Rho]^12) \[Omega]+26011238400 (9 Rn^2 \[Rho]^4 \[Omega]^2+5 (-24+Rn^2 \[Omega]^2)-16 \[Rho]^2 (-15+Rn^2 \[Omega]^2))+4032 G^2 Rn^2 (714000-923 Rn^2 \[Omega]^2+288 Rn^2 \[Rho]^10 \[Omega]^2+5040 \[Rho]^6 (-416+Rn^2 \[Omega]^2)-350 \[Rho]^8 (-912+5 Rn^2 \[Omega]^2)+280 \[Rho]^2 (-11856+17 Rn^2 \[Omega]^2)-315 \[Rho]^4 (-13392+23 Rn^2 \[Omega]^2))) Cos[2 \[Phi]]) 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+(\[Rho] Cos[\[Phi]]^2 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])/Rn+1/59454259200 G Rn \[Rho] (-1+\[Rho]^2)^2 (G^3 Rn^2 (4979-2792 \[Rho]^2+777 \[Rho]^4-134 \[Rho]^6+5 \[Rho]^8)-116121600 \[Omega]-16 G^2 Rn^2 (-3111+1228 \[Rho]^2-208 \[Rho]^4+36 \[Rho]^6) \[Omega]-6720 G (7296-17 Rn^2 \[Omega]^2+Rn^2 \[Rho]^4 \[Omega]^2+2 \[Rho]^2 (-1056+Rn^2 \[Omega]^2))) Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+(G Rn \[Rho] (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Sin[\[Phi]]^2 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])/4608-1/737280 G \[Rho] (-1+\[Rho]^2) (46080+G^2 Rn^2 (-19+21 \[Rho]^2-9 \[Rho]^4+\[Rho]^6)-40 G Rn^2 (3-3 \[Rho]^2+\[Rho]^4) \[Omega]) Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1/8 G \[Rho] (-1+\[Rho]^2) Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1/59929893273600 G \[Rho] (-1+\[Rho]^2) (G^4 Rn^4 (145690-240206 \[Rho]^2+174649 \[Rho]^4-70547 \[Rho]^6+19123 \[Rho]^8-2801 \[Rho]^10+160 \[Rho]^12)-325140480 G Rn^2 (101-89 \[Rho]^2+21 \[Rho]^4) \[Omega]-252 G^3 Rn^4 (-6017+9735 \[Rho]^2-6775 \[Rho]^4+2465 \[Rho]^6-545 \[Rho]^8+47 \[Rho]^10) \[Omega]+26011238400 (120+Rn^2 (-5+3 \[Rho]^2) \[Omega]^2)+4032 G^2 Rn^2 (-714000+923 Rn^2 \[Omega]^2+48 Rn^2 \[Rho]^8 \[Omega]^2+\[Rho]^2 (945840-1457 Rn^2 \[Omega]^2)+\[Rho]^6 (63840-302 Rn^2 \[Omega]^2)+\[Rho]^4 (-460320+958 Rn^2 \[Omega]^2))) Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])+1/(2 Rn \[Rho]^2)(2 Rn \[Lambda] \[Rho]^2 v\[Zeta][\[Rho],\[Phi]]+G Rn \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 (
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+\[Rho] (
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+\[Rho] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]))),1/(Rn \[Rho]^4) (4 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-Rn \[Lambda] \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "4"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+\[Rho] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-Rn \[Lambda] \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 \[Rho] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-\[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-Rn \[Lambda] \[Rho]^4 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2 \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2 \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1/4608 \[Kappa] \[Rho] (4608 G Rn \[Rho]^4 Sin[\[Phi]] v\[Zeta][\[Rho],\[Phi]]+2304 G Rn \[Rho]^2 (-1+\[Rho]^2) Cos[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 Rn \[Rho]^2 \[Omega] Cos[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4608 Rn \[Lambda] \[Rho]^2 Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2 G Rn^2 (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 G Rn^2 (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+6 G Rn^2 \[Rho]^2 (G (9-60 \[Rho]^2+35 \[Rho]^4)+48 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+6 G Rn^2 \[Rho]^2 (G (9-20 \[Rho]^2+7 \[Rho]^4)+16 (3-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-18432 Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2 G Rn^2 (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-G Rn^2 (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2304 G Rn \[Rho]^3 (-1+\[Rho]^2) Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 Rn \[Rho]^3 \[Omega] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 \[Rho] Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4608 Rn \[Lambda] \[Rho]^3 Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-G Rn^2 \[Rho] (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6 G Rn^2 \[Rho]^3 (G (9-20 \[Rho]^2+7 \[Rho]^4)+16 (3-5 \[Rho]^2) \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 \[Rho] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-G Rn^2 \[Rho] (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9216 \[Rho] Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+G Rn^2 \[Rho] (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9216 \[Rho]^2 Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+G Rn^2 \[Rho]^2 (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9216 \[Rho]^2 Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-G Rn^2 \[Rho]^2 (-1+\[Rho]^2) (G (4-23 \[Rho]^2+7 \[Rho]^4)+24 (1-5 \[Rho]^2) \[Omega]) Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9216 \[Rho]^3 Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+G Rn^2 \[Rho]^3 (-1+\[Rho]^2)^2 (G (-4+\[Rho]^2)-24 \[Omega]) Cos[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])-1/59454259200 \[Kappa]^2 \[Rho]^2 (322560 G Rn \[Rho]^4 (115200+G^2 Rn^2 (-20+30 \[Rho]^2-15 \[Rho]^4+2 \[Rho]^6)-20 G Rn^2 (6-8 \[Rho]^2+3 \[Rho]^4) \[Omega]) Sin[2 \[Phi]] v\[Zeta][\[Rho],\[Phi]]-309657600 Rn \[Rho]^2 (192 \[Lambda]-3 G^2 Rn (1-4 \[Rho]^2+2 \[Rho]^4)+16 G Rn (-1+3 \[Rho]^2) \[Omega]+2 G Rn \[Rho]^2 (G (-3+2 \[Rho]^2)-12 \[Omega]) Cos[2 \[Phi]]) \[Psi][\[Rho],\[Phi]]-18579456000 G Rn \[Rho]^2 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1532160 G^3 Rn^3 \[Rho]^2 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+18579456000 G Rn \[Rho]^4 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3225600 G^3 Rn^3 \[Rho]^4 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2419200 G^3 Rn^3 \[Rho]^6 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-806400 G^3 Rn^3 \[Rho]^8 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+80640 G^3 Rn^3 \[Rho]^10 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9676800 G^2 Rn^3 \[Rho]^2 \[Omega] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-19353600 G^2 Rn^3 \[Rho]^4 \[Omega] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+12902400 G^2 Rn^3 \[Rho]^6 \[Omega] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3225600 G^2 Rn^3 \[Rho]^8 \[Omega] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-18579456000 G Rn \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1532160 G^3 Rn^3 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+18579456000 G Rn \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3225600 G^3 Rn^3 \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2419200 G^3 Rn^3 \[Rho]^6 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-806400 G^3 Rn^3 \[Rho]^8 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+80640 G^3 Rn^3 \[Rho]^10 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9676800 G^2 Rn^3 \[Rho]^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-19353600 G^2 Rn^3 \[Rho]^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+12902400 G^2 Rn^3 \[Rho]^6 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3225600 G^2 Rn^3 \[Rho]^8 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 Rn \[Lambda] \[Rho]^2 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+619315200 G Rn^2 \[Omega] Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+51609600 G^2 Rn^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1347010560 G^2 Rn^2 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-153000 G^4 Rn^4 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-5031936000 G^2 Rn^2 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+725760 G^4 Rn^4 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2580480000 G^2 Rn^2 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-806400 G^4 Rn^4 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+403200 G^4 Rn^4 \[Rho]^8 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-100800 G^4 Rn^4 \[Rho]^10 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5760 G^4 Rn^4 \[Rho]^12 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2786918400 G Rn^2 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1430400 G^3 Rn^4 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-7741440000 G Rn^2 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5913600 G^3 Rn^4 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4838400 G^3 Rn^4 \[Rho]^6 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1720320 G^3 Rn^4 \[Rho]^8 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-403200 G^3 Rn^4 \[Rho]^10 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2903040 G^2 Rn^4 \[Rho]^2 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+8601600 G^2 Rn^4 \[Rho]^4 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2580480 G^2 Rn^4 \[Rho]^8 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+29727129600 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25804800 G^2 Rn^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-58060800 G^2 Rn^2 \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G^2 Rn^2 \[Rho]^4 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6451200 G^2 Rn^2 \[Rho]^6 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+154828800 G Rn^2 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-309657600 G Rn^2 \[Rho]^2 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+154828800 G Rn^2 \[Rho]^4 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-148635648000 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+20643840 G^2 Rn^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9958 G^4 Rn^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-50319360 G^2 Rn^2 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25500 G^4 Rn^4 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G^2 Rn^2 \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-22680 G^4 Rn^4 \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-9031680 G^2 Rn^2 \[Rho]^6 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+8960 G^4 Rn^4 \[Rho]^6 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2100 G^4 Rn^4 \[Rho]^8 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+288 G^4 Rn^4 \[Rho]^10 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-10 G^4 Rn^4 \[Rho]^12 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-232243200 G Rn^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-99552 G^3 Rn^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+464486400 G Rn^2 \[Rho]^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+238400 G^3 Rn^4 \[Rho]^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-232243200 G Rn^2 \[Rho]^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-184800 G^3 Rn^4 \[Rho]^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+53760 G^3 Rn^4 \[Rho]^6 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-8960 G^3 Rn^4 \[Rho]^8 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1152 G^3 Rn^4 \[Rho]^10 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-228480 G^2 Rn^4 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+483840 G^2 Rn^4 \[Rho]^2 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-268800 G^2 Rn^4 \[Rho]^4 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+13440 G^2 Rn^4 \[Rho]^8 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-59454259200 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+23224320 G^2 Rn^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4979 G^4 Rn^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-166440960 G^2 Rn^2 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25500 G^4 Rn^4 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+193536000 G^2 Rn^2 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-34020 G^4 Rn^4 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-50319360 G^2 Rn^2 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+17920 G^4 Rn^4 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-5250 G^4 Rn^4 \[Rho]^8 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+864 G^4 Rn^4 \[Rho]^10 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-35 G^4 Rn^4 \[Rho]^12 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G Rn^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-49776 G^3 Rn^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+238400 G^3 Rn^4 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+193536000 G Rn^2 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-277200 G^3 Rn^4 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+107520 G^3 Rn^4 \[Rho]^6 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-22400 G^3 Rn^4 \[Rho]^8 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3456 G^3 Rn^4 \[Rho]^10 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-114240 G^2 Rn^4 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+483840 G^2 Rn^4 \[Rho]^2 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-403200 G^2 Rn^4 \[Rho]^4 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+33600 G^2 Rn^4 \[Rho]^8 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"0", ",", "3"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-37158912000 G Rn \[Rho]^3 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3064320 G^3 Rn^3 \[Rho]^3 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+37158912000 G Rn \[Rho]^5 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6451200 G^3 Rn^3 \[Rho]^5 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4838400 G^3 Rn^3 \[Rho]^7 Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^3 \[Rho]^5 \[Omega] Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25804800 G^2 Rn^3 \[Rho]^7 \[Omega] Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6451200 G^2 Rn^3 \[Rho]^9 \[Omega] Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-806400 G^3 Rn^3 \[Rho]^9 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+80640 G^3 Rn^3 \[Rho]^11 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+9676800 G^2 Rn^3 \[Rho]^3 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["v\[Zeta]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+89181388800 \[Rho] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+464486400 G^2 Rn^2 \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-29727129600 Rn \[Lambda] \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-928972800 G^2 Rn^2 \[Rho]^5 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+309657600 G^2 Rn^2 \[Rho]^7 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2477260800 G Rn^2 \[Rho]^3 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3715891200 G Rn^2 \[Rho]^5 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-89181388800 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-2580480 G^2 Rn^2 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4979 G^4 Rn^4 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1575383040 G^2 Rn^2 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+165750 G^4 Rn^4 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-29727129600 Rn \[Lambda] \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3096576000 G^2 Rn^2 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-374220 G^4 Rn^4 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1085091840 G^2 Rn^2 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+273280 G^4 Rn^4 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-101850 G^4 Rn^4 \[Rho]^9 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+20304 G^4 Rn^4 \[Rho]^11 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-965 G^4 Rn^4 \[Rho]^13 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-193536000 G Rn^2 \[Rho] \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-49776 G^3 Rn^4 \[Rho] \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3638476800 G Rn^2 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1549600 G^3 Rn^4 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5999616000 G Rn^2 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-3049200 G^3 Rn^4 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1639680 G^3 Rn^4 \[Rho]^7 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-434560 G^3 Rn^4 \[Rho]^9 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+81216 G^3 Rn^4 \[Rho]^11 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-114240 G^2 Rn^4 \[Rho] \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3144960 G^2 Rn^4 \[Rho]^3 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4435200 G^2 Rn^4 \[Rho]^5 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+651840 G^2 Rn^4 \[Rho]^9 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-237817036800 \[Rho] Cos[\[Phi]] Sin[\[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-28385280 G^2 Rn^2 \[Rho] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4979 G^4 Rn^4 \[Rho] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+65802240 G^2 Rn^2 \[Rho]^3 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25500 G^4 Rn^4 \[Rho]^3 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^2 \[Rho]^5 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-34020 G^4 Rn^4 \[Rho]^5 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1290240 G^2 Rn^2 \[Rho]^7 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+17920 G^4 Rn^4 \[Rho]^7 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-5250 G^4 Rn^4 \[Rho]^9 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+864 G^4 Rn^4 \[Rho]^11 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-35 G^4 Rn^4 \[Rho]^13 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-348364800 G Rn^2 \[Rho] \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-49776 G^3 Rn^4 \[Rho] \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1083801600 G Rn^2 \[Rho]^3 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+238400 G^3 Rn^4 \[Rho]^3 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-735436800 G Rn^2 \[Rho]^5 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-277200 G^3 Rn^4 \[Rho]^5 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+107520 G^3 Rn^4 \[Rho]^7 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-22400 G^3 Rn^4 \[Rho]^9 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3456 G^3 Rn^4 \[Rho]^11 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-114240 G^2 Rn^4 \[Rho] \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+483840 G^2 Rn^4 \[Rho]^3 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-403200 G^2 Rn^4 \[Rho]^5 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+33600 G^2 Rn^4 \[Rho]^9 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 \[Rho] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-25804800 G^2 Rn^2 \[Rho] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+58060800 G^2 Rn^2 \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^2 \[Rho]^5 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+6451200 G^2 Rn^2 \[Rho]^7 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho] \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+309657600 G Rn^2 \[Rho]^3 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho]^5 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-23224320 G^2 Rn^2 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4979 G^4 Rn^4 \[Rho] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+54190080 G^2 Rn^2 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-12750 G^4 Rn^4 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^2 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+11340 G^4 Rn^4 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+7741440 G^2 Rn^2 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4480 G^4 Rn^4 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1050 G^4 Rn^4 \[Rho]^9 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-144 G^4 Rn^4 \[Rho]^11 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5 G^4 Rn^4 \[Rho]^13 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G Rn^2 \[Rho] \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+49776 G^3 Rn^4 \[Rho] \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-77414400 G Rn^2 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-119200 G^3 Rn^4 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G Rn^2 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+92400 G^3 Rn^4 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-26880 G^3 Rn^4 \[Rho]^7 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4480 G^3 Rn^4 \[Rho]^9 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-576 G^3 Rn^4 \[Rho]^11 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+114240 G^2 Rn^4 \[Rho] \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-241920 G^2 Rn^4 \[Rho]^3 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+134400 G^2 Rn^4 \[Rho]^5 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6720 G^2 Rn^4 \[Rho]^9 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"1", ",", "2"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+208089907200 \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-51609600 G^2 Rn^2 \[Rho]^2 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+232243200 G^2 Rn^2 \[Rho]^4 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-232243200 G^2 Rn^2 \[Rho]^6 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+51609600 G^2 Rn^2 \[Rho]^8 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-309657600 G Rn^2 \[Rho]^2 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1238630400 G Rn^2 \[Rho]^4 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-928972800 G Rn^2 \[Rho]^6 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+89181388800 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+2580480 G^2 Rn^2 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4979 G^4 Rn^4 \[Rho]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-119992320 G^2 Rn^2 \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-12750 G^4 Rn^4 \[Rho]^4 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+154828800 G^2 Rn^2 \[Rho]^6 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+11340 G^4 Rn^4 \[Rho]^6 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-37416960 G^2 Rn^2 \[Rho]^8 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4480 G^4 Rn^4 \[Rho]^8 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1050 G^4 Rn^4 \[Rho]^10 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-144 G^4 Rn^4 \[Rho]^12 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5 G^4 Rn^4 \[Rho]^14 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+193536000 G Rn^2 \[Rho]^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+49776 G^3 Rn^4 \[Rho]^2 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-1006387200 G Rn^2 \[Rho]^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-119200 G^3 Rn^4 \[Rho]^4 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+812851200 G Rn^2 \[Rho]^6 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+92400 G^3 Rn^4 \[Rho]^6 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-26880 G^3 Rn^4 \[Rho]^8 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4480 G^3 Rn^4 \[Rho]^10 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-576 G^3 Rn^4 \[Rho]^12 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+114240 G^2 Rn^4 \[Rho]^2 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-241920 G^2 Rn^4 \[Rho]^4 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+134400 G^2 Rn^4 \[Rho]^6 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6720 G^2 Rn^4 \[Rho]^10 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-59454259200 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+23224320 G^2 Rn^2 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4979 G^4 Rn^4 \[Rho]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-166440960 G^2 Rn^2 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+25500 G^4 Rn^4 \[Rho]^4 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+193536000 G^2 Rn^2 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-34020 G^4 Rn^4 \[Rho]^6 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-50319360 G^2 Rn^2 \[Rho]^8 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+17920 G^4 Rn^4 \[Rho]^8 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-5250 G^4 Rn^4 \[Rho]^10 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+864 G^4 Rn^4 \[Rho]^12 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-35 G^4 Rn^4 \[Rho]^14 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G Rn^2 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-49776 G^3 Rn^4 \[Rho]^2 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+238400 G^3 Rn^4 \[Rho]^4 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+193536000 G Rn^2 \[Rho]^6 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-277200 G^3 Rn^4 \[Rho]^6 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+107520 G^3 Rn^4 \[Rho]^8 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-22400 G^3 Rn^4 \[Rho]^10 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+3456 G^3 Rn^4 \[Rho]^12 \[Omega] Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-114240 G^2 Rn^4 \[Rho]^2 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+483840 G^2 Rn^4 \[Rho]^4 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-403200 G^2 Rn^4 \[Rho]^6 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+33600 G^2 Rn^4 \[Rho]^10 \[Omega]^2 Sin[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"2", ",", "1"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-25804800 G^2 Rn^2 \[Rho]^3 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+58060800 G^2 Rn^2 \[Rho]^5 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^2 \[Rho]^7 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+6451200 G^2 Rn^2 \[Rho]^9 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho]^3 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+309657600 G Rn^2 \[Rho]^5 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-154828800 G Rn^2 \[Rho]^7 \[Omega] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+59454259200 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-23224320 G^2 Rn^2 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4979 G^4 Rn^4 \[Rho]^3 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+54190080 G^2 Rn^2 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-12750 G^4 Rn^4 \[Rho]^5 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-38707200 G^2 Rn^2 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+11340 G^4 Rn^4 \[Rho]^7 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+7741440 G^2 Rn^2 \[Rho]^9 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-4480 G^4 Rn^4 \[Rho]^9 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+1050 G^4 Rn^4 \[Rho]^11 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-144 G^4 Rn^4 \[Rho]^13 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+5 G^4 Rn^4 \[Rho]^15 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G Rn^2 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+49776 G^3 Rn^4 \[Rho]^3 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-77414400 G Rn^2 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-119200 G^3 Rn^4 \[Rho]^5 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+38707200 G Rn^2 \[Rho]^7 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+92400 G^3 Rn^4 \[Rho]^7 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-26880 G^3 Rn^4 \[Rho]^9 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+4480 G^3 Rn^4 \[Rho]^11 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-576 G^3 Rn^4 \[Rho]^13 \[Omega] Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+114240 G^2 Rn^4 \[Rho]^3 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-241920 G^2 Rn^4 \[Rho]^5 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]+134400 G^2 Rn^4 \[Rho]^7 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]]-6720 G^2 Rn^4 \[Rho]^11 \[Omega]^2 Cos[2 \[Phi]] 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"3", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])+\[Rho]^4 
\!\(\*SuperscriptBox["\[Psi]", 
TagBox[
RowBox[{"(", 
RowBox[{"4", ",", "0"}], ")"}],
Derivative],
MultilineFunction->None]\)[\[Rho],\[Phi]])};


(* ::Input:: *)
(*eqs\[Phi]r[\[Lambda],0,0,0,G,R]//Expand*)


(* ::Subsubsection::Closed:: *)
(*\:041a\:0420\:0421 \:0441 \:0434\:0440\:043e\:0431\:043d\:043e\:0439 \:0441\:0435\:0442\:043a\:043e\:0439 \:0438 \:0446\:0435\:043d\:0442\:0440\:0430\:043b\:044c\:043d\:044b\:043c\:0438 \:0440\:0430\:0437\:043d\:043e\:0441\:0442\:044f\:043c\:0438*)


(*\:0422.\:043a. \:0443 v\[Zeta] \:043c\:0430\:043a\:0441\:0438\:043c\:0443\:043c 2 \:043f\:0440\:043e\:0438\:0437\:0432\:043e\:0434\:043d\:0430\:044f \:043f\:043e \[Rho], \:0430 \:0443 \[Psi] \:043c\:0430\:043a\:0441\:0438\:043c\:0443\:043c 4, \:0442\:043e \:0444\:0438\:043a\:0442\:0438\:0432\:043d\:044b\:0435 \:0441\:043b\:043e\:0438 - \:0443 v\[Zeta](f)=1, \:0443 \[Psi](g)=2*)
FiniteMatrix4Eigen[nr_,n\[Phi]_,subst___]:=Block[{hr=1/nr,h\[Phi]=(2\[Pi])/n\[Phi],unk,unkmain,unkfict,unkvr,i,ghv,gh\[Psi],s,order,lhs,rhs,\[Lambda],bcr,bc\[Phi],bc},
If[OddQ[n\[Phi]],Print["\:043a\:043e\:043b-\:0432\:043e \:0443\:0437\:043b\:043e\:0432 \:043f\:043e \[Phi] \:0434\:043e\:043b\:0436\:043d\:043e \:0431\:044b\:0442\:044c \:0447\:0451\:0442\:043d\:044b\:043c (\:0434\:043b\:044f \:0441\:043e\:043e\:0442\:0432\:0435\:0442\:0441\:0442\:0432\:0438\:044f \:0432 \:0446\:0435\:043d\:0442\:0440\:0435)"];Return[]];
ghv=1;gh\[Psi]=2;
unk=Join[Table[f[i+1/2,j],{i,0-ghv,nr+ghv-1},{j,0,n\[Phi]-1}],Table[g[i+1/2,j],{i,0-gh\[Psi],nr+gh\[Psi]-1},{j,0,n\[Phi]-1}]];
unkmain=Join[Table[f[i+1/2,j],{i,0,nr-1},{j,0,n\[Phi]-1}],Table[g[i+1/2,j],{i,0,nr-1},{j,0,n\[Phi]-1}]];
coorlist=Flatten[Table[{(i+1/2)hr,j*h\[Phi]},{i,0,nr-1},{j,0,n\[Phi]-1}],1];
unkfict=Complement[unk,unkmain];(*\:0442\:043e\:043b\:044c\:043a\:043e \:0432\:0434\:043e\:043b\:044c \:0440\:0430\:0434\:0438\:0443\:0441\:0430 \:0435\:0441\:0442\:044c*)
FullDot[m1_,m2_]:=Total[Flatten[m1*m2]];
pdersam[buk_,ndr_,nd\[Phi]_,s_]:=FullDot[
\!\(\*SuperscriptBox[
RowBox[{"{", 
RowBox[{"NDCoefficientList", "[", 
RowBox[{"ndr", ",", "s"}], "]"}], "}"}], "\[Transpose]"]\).{NDCoefficientList[nd\[Phi],s]},Table[buk[$i,$k],{$i,i-(s-1)/2,i+(s-1)/2},{$k,j-(s-1)/2,j+(s-1)/2}]]/hr^ndr/h\[Phi]^nd\[Phi];
rdersam[buk_,\[Phi]i_,order_,s_]:=Table[buk[j,\[Phi]i],{j,i-(s-1)/2,i+(s-1)/2}].NDCoefficientList[order,s]/hr^order;
subs=Join[{\[Rho]->i hr,\[Phi]->j h\[Phi]},{v\[Zeta][\[Rho],\[Phi]]->f[i,j],Derivative[a_,b_][v\[Zeta]][\[Rho],\[Phi]]->pdersam[f,a,b,2ghv+1]},{\[Psi][\[Rho],\[Phi]]->g[i,j],Derivative[a_,b_][\[Psi]][\[Rho],\[Phi]]->pdersam[g,a,b,2gh\[Psi]+1]},{subst}];
rhs=-D[eqs\[Phi]r[\[Lambda],\[Omega],\[Epsilon],\[Kappa],G,R],\[Lambda]]/.subs;
lhs=Coefficient[eqs\[Phi]r[\[Lambda],\[Omega],\[Epsilon],\[Kappa],G,R],\[Lambda],0]/.subs;
bcr=Join[Flatten[Table[{rdersam[f,j,0,2ghv]/.i->nr,rdersam[g,j,0,2gh\[Psi]]/.i->nr,rdersam[g,j,1,2gh\[Psi]]/.i->nr},{j,0,n\[Phi]-1}]],Table[f[i,j_]->f[-i,Mod[j+n\[Phi]/2,n\[Phi]]],{i,-ghv+1/2,-1/2}],Table[g[i,j_]->g[-i,Mod[j+n\[Phi]/2,n\[Phi]]],{i,-gh\[Psi]+1/2,-1/2}]];
bc\[Phi]=Join[Table[f[i_,j]->f[i,n\[Phi]+j],{j,-ghv,-1}],Table[f[i_,j]->f[i,j-n\[Phi]],{j,n\[Phi],n\[Phi]+ghv-1}],Table[g[i_,j]->g[i,n\[Phi]+j],{j,-gh\[Psi],-1}],Table[g[i_,j]->g[i,j-n\[Phi]],{j,n\[Phi],n\[Phi]+gh\[Psi]-1}]];
bc=Select[Join[bcr,bc\[Phi]],Head[#]=!=Rule&];
unkvr=Select[Flatten[unkfict],First[#]>0&];
virfict=First[Solve[Thread[bc==0],unkvr]];
virfict=Join[virfict,Select[Join[bcr,bc\[Phi]],Head[#]==Rule&]];
(*fict=unkfict/.virfict;*)
unkmain=Flatten[unkmain];
rhs1=Coefficient[#,unkmain]&/@Flatten[Table[rhs,{i,1/2,nr-1/2},{j,0,n\[Phi]-1}]/.virfict];
lhs1=Coefficient[#,unkmain]&/@Flatten[Table[lhs,{i,1/2,nr-1/2},{j,0,n\[Phi]-1}]/.virfict];(*//Timing//Print;*)
(*rhs=Coefficient[#,unk]&/@Join[Table[0,{i,2},{j,n+sm-1}],Table[rhs,{i,1/2,n-1/2}]/\[Omega],Table[0,{i,2},{j,n+sm-1}]];
lhs=Coefficient[#,unk]&/@Join[{dersam[0,sm-1]/.i->0,dersam[1,sm-1]/.i->0},Table[lhs,{i,1/2,n-1/2}],{dersam[1,sm-1]/.i->n,dersam[0,sm-1]/.i->n}];*)
(*Return[rhs.Inverse[lhs]];*)
Return[{lhs1,rhs1}];
];


(* ::Subsection::Closed:: *)
(*\:0424\:0443\:043d\:043a\:0446\:0438\:0438 \:043d\:0430\:0445\:043e\:0436\:0434\:0435\:043d\:0438\:044f \:0438\:043d\:043a\:0440\:0435\:043c\:0435\:043d\:0442\:043e\:0432*)


(* ::Subsubsection::Closed:: *)
(*\:041f\:043e\:043b\:0443\:0447\:0435\:043d\:0438\:0435 \:0441.\:0437. \:0438 \:0441.\:0432. \:0441 \:043f\:043e\:043c\:043e\:0449\:044c\:044e Eigen...[Inverse[a].m] (\:043c\:0435\:043d\:0435\:0435 \:0443\:0441\:0442\:043e\:0439\:0447\:0438\:0432\:043e)*)


(* ::Input:: *)
(*GetIncrements[n_,m_,k1_,R1_]:=Eigenvalues[Inverse[Last[#]].First[#]&[N[FiniteMatrix4Eigen[n,m,k->k1,R->R1]]]];*)


(* ::Input:: *)
(*GetEigenWave[n1_,m_,k1_,R1_,mode_:1]:=Block[{eigval,eigvec,nom,syst},syst=Inverse[Last[#]].First[#]&[N[FiniteMatrix4Eigen[n1,m,k->k1,R->R1]]];*)
(*{eigval,eigvec}=Select[Transpose[Eigensystem[syst]],NumericQ[First[#]]&]//Transpose;*)
(*nom=Flatten[Position[eigval,Sort[eigval,Re[#1]>Re[#2]&][[mode]]]]//First;*)
(*Print["Main eigen value is ",eigval[[nom]]];*)
(*Return[eigvec[[nom]]];];*)


(* ::Subsubsection::Closed:: *)
(*\:041f\:043e\:043b\:0443\:0447\:0435\:043d\:0438\:0435 \:0441.\:0437. \:0438 \:0441.\:0432. \:0441 \:043f\:043e\:043c\:043e\:0449\:044c\:044e Eigen...[{m,a}]*)


GetIncrementsM[mat_,Re1_]:=Select[Eigenvalues[mat[Re1]],NumericQ];


GetEigenWaveM[syst_,mode_:1]:=Block[{eigval,eigvec,nom},
{eigval,eigvec}=Select[Transpose[Eigensystem[syst]],NumericQ[First[#]]&]//Transpose;
nom=Flatten[Position[eigval,Sort[eigval,Re[#1]>Re[#2]&][[mode]]]]//First;
Print["Main eigen value is ",eigval[[nom]]];
Return[eigvec[[nom]]];];


GetIncrements[nr_,n\[Phi]_,\[Kappa]1_,R1_,subst___]:=Select[Eigenvalues[N[FiniteMatrix4Eigen[nr,n\[Phi],subst,\[Kappa]->\[Kappa]1,R->R1,\[Omega]->0,\[Epsilon]->0,G->4]]],NumericQ];


GetEigenWave[n1_,m_,k1_,R1_,mode_:1]:=Block[{eigval,eigvec,nom,syst},syst=N[FiniteMatrix4Eigen[n1,m,k->k1,R->R1,\[Omega]->0,\[Epsilon]->0,G->4]];
{eigval,eigvec}=Select[Transpose[Eigensystem[syst]],NumericQ[First[#]]&]//Transpose;
nom=Flatten[Position[eigval,Sort[eigval,Re[#1]>Re[#2]&][[mode]]]]//First;
Print["Main eigen value is ",eigval[[nom]]];
Return[eigvec[[nom]]];];


GetMainIncrement[n_,m_,k1_,R1_,num_:1]:=(*GetMainIncrement[n,k1,R1,num]=*)(Print[{n,k1,R1}];Take[Sort[Re/@GetIncrementsM[mat[R1]]],{-num}]//First);


(* ::Subsubsection::Closed:: *)
(*\:041f\:0440\:043e\:0432\:0435\:0440\:043a\:0438*)


(* ::Input:: *)
(*Take[Sort[GetIncrements[20,0,1,100],Re[#1]>Re[#2]&],10]*)


(* ::Input:: *)
(*GetMainIncrement[100,0,1,100,2]*)


(* ::Input:: *)
(*(*\:041e\:0442\:043a\:043b\:043e\:043d\:0435\:043d\:0438\:044f \:0432 \:043e\:043f\:0440\:0435\:0434\:0435\:043b\:0438\:0442\:0435\:043b\:0435 \:043f\:043e\:0441\:043b\:0435 \:043f\:043e\:0434\:0441\:0442\:0430\:043d\:043e\:0432\:043a\:0438 \:0441\:043e\:0431\:0441\:0442\:0432\:0435\:043d\:043d\:043e\:0433\:043e \:0437\:043d\:0430\:0447\:0435\:043d\:0438\:044f*)
(*With[{n2=3,m=0,k2=1,R2=100,mod=1},Det[SetPrecision[First[#]-Sort[GetIncrements[n2,m,k2,R2],Re[#1]>Re[#2]&][[mod]]Last[#],1000]]&[SetPrecision[FiniteMatrix4Eigen[n2,m,k->k2,R->R2],1000]]]*)*)


(* ::Input:: *)
(*(*\:041e\:0442\:043a\:043b\:043e\:043d\:0435\:043d\:0438\:044f \:0432 \:0432\:0435\:043a\:0442\:043e\:0440\:0435 \:043f\:043e\:0441\:043b\:0435 \:043f\:043e\:0434\:0441\:0442\:0430\:043d\:043e\:0432\:043a\:0438 \:0441\:043e\:0431\:0441\:0442\:0432\:0435\:043d\:043d\:044b\:0445 \:0437\:043d\:0430\:0447\:0435\:043d\:0438\:0439 \:0438 \:0432\:0435\:043a\:0442\:043e\:0440\:043e\:0432*)*)
(*With[{n2=300,m=0,k2=1,R2=1000,mod=2},(First[#]-Sort[GetIncrements[n2,m,k2,R2],Re[#1]>Re[#2]&][[mod]]Last[#]).GetEigenWave[n2,m,k2,R2,mod]&[FiniteMatrix4Eigen[n2,m,k->k2,R->R2]]]//Abs//PrintRange;*)


(* ::Input:: *)
(*PrintRange[GetIncrementsM[mat,0.1]]*)


(* ::Input:: *)
(*mat[R_]=SparseArray[N[FiniteMatrix4Eigen[20,20,\[Omega]->0,\[Epsilon]->0,\[Kappa]->0,G->4]]];*)


(* ::Input:: *)
(*matk0G4=mat[R];*)


(* ::Input:: *)
(*mat[R_]=SparseArray[N[FiniteMatrix4Eigen[20,20,\[Omega]->0,\[Epsilon]->0,\[Kappa]->0.1,G->4]]];*)


(* ::Input:: *)
(*matk01G4=mat[R];*)


(* ::Input:: *)
(*Take[Sort[Re[incsR10k01G4]],-20]//Reverse*)


(* ::Input:: *)
(*PrintRange[Re[incsR10k01G4-incsR10k0G0]];*)


(* ::Input:: *)
(*incsR1k0G4=Sort[GetIncrementsM[Function[R,Evaluate[matk0G4]],1],Re[#1]>Re[#2]&];*)


(* ::Input:: *)
(*incsR10k01G4=Sort[GetIncrementsM[Function[R,Evaluate[matk01G4]],300],Re[#1]>Re[#2]&];*)


(* ::Input:: *)
(*Sort[GetIncrementsM[mat,1],Re[#1]>Re[#2]&]//Chop*)


(* ::Subsection::Closed:: *)
(*\:0418\:0441\:0441\:043b\:0435\:0434\:043e\:0432\:0430\:043d\:0438\:0435 \:0433\:043b\:0430\:0432\:043d\:044b\:0445 \:0433\:0430\:0440\:043c\:043e\:043d\:0438\:043a*)


(* ::Input:: *)
(*NumMode[mat_,n\[Phi]_]:=Block[{funcs=Partition[mat,Length[mat]/2],func,lf},*)
(*func=If[Max[Abs[Chop[First[funcs]]]]>Max[Abs[funcs]]/10^5,First[funcs],Last[funcs]];*)
(*lf=Take[#,Length[#]/2]&[First[Abs[Fourier[Partition[func,n\[Phi]]]]]];*)
(*Return[First[Flatten[Position[lf,Max[lf]]]]-1];*)
(*];*)


(* ::Input:: *)
(*matsolv=GetEigenWaveM[mat[1],3];*)


(* ::Input:: *)
(*matsolv=GetEigenWaveM[Evaluate[Normal[matk01G4]/.R->1000],12];*)


(* ::Input:: *)
(*FreeQ[Chop[matsolv],\[ImaginaryI]]*)


(* ::Subsubsection::Closed:: *)
(*\:0421\:0445\:043e\:0434\:0438\:043c\:043e\:0441\:0442\:044c*)


(* ::Input:: *)
(*linctor1=Table[Sort[GetIncrements[2n,2n,0,1],Re[#1]>Re[#2]&]//Chop,{n,1,10}];*)


(* ::Input:: *)
(*nm=NumMode[GetEigenWaveM[mat[1],#],20]&/@Range[50]*)


(* ::Input:: *)
(*Take[Last[linctor1],50]*)


(* ::Input:: *)
(*Flatten[Take[Last[linctor1],50][[#]]&/@Position[nm,1]]*)


(* ::Input:: *)
(*inctorlim=ListLimit[#,ApproximationReport->None,CutValues->False]&/@(Drop[Transpose[{Range[3,10],#}],4]&/@Transpose[Take[#,60]&/@Drop[linctor1,2]])*)


(* ::Input:: *)
(*Flatten[inctorlim[[#]]&/@Position[nm,1]]*)


(* ::Input:: *)
(*PrintRange[#[[3]]&/@Drop[linctor1,2]];*)


(* ::Input:: *)
(*ListLimit[#,ApproximationReport->LimitPlot]&/@(Transpose[{First/@Take[linctor1,-Length[#]],#}]&/@Re[Transpose[Last/@Drop[linctor1,8]]])*)


(* ::Subsubsection:: *)
(*\:0412\:0438\:0437\:0443\:0430\:043b\:0438\:0437\:0430\:0446\:0438\:044f*)


(* ::Input:: *)
(*Pize[l_,add_]:=Append[l,{First[#],Last[#]}&[First[l]]+add];*)
(*Pize[l_]:=Append[l,First[l]];*)
(*PizeAll[l_]:=Join[l,Block[{tmp=#},tmp[[2]]+=2\[Pi];tmp]&/@Select[l,#[[2]]==0&]];*)


(* ::Input:: *)
(*{v\[Zeta]si,\[Psi]si}=Interpolation[PizeAll[MapThread[Append,{coorlist,#}]],PeriodicInterpolation->{False,True},InterpolationOrder->{1,1}]&/@Partition[Re[matsolv],Length[matsolv]/2];*)


(* ::Text:: *)
(*\:0417\:0430\:0432\:0438\:0441\:0438\:043c\:043e\:0441\:0442\:044c \:043e\:0442 \:0440\:0430\:0434\:0438\:0443\:0441\:0430*)


(* ::Input:: *)
(*Plot[v\[Zeta]si[r,0.4`],{r,coorlist[[1,1]],coorlist[[-1,1]]},PlotRange->All];Plot[\[Psi]si[r,0.4`],{r,coorlist[[1,1]],coorlist[[-1,1]]},PlotRange->All]*)


(* ::Text:: *)
(*\:0417\:0430\:0432\:0438\:0441\:0438\:043c\:043e\:0441\:0442\:044c \:043e\:0442 \:0443\:0433\:043b\:0430*)


(* ::Input:: *)
(*Plot[v\[Zeta]si[1/4,\[Phi]],{\[Phi],0,2 \[Pi]}]*)
(*Plot[\[Psi]si[1/4,\[Phi]],{\[Phi],0,2 \[Pi]}]*)


(* ::Text:: *)
(*\:0414\:0432\:0443\:043c\:0435\:0440\:043d\:044b\:0435 \:043a\:0430\:0440\:0442\:0438\:043d\:043a\:0438 - Density*)


(* ::Input:: *)
(*PolarDensityPlot[v\[Zeta]si[r,f],{r,coorlist[[1,1]],coorlist[[-1,1]]},{f}];*)
(*PolarDensityPlot[\[Psi]si[r,f],{r,coorlist[[1,1]],coorlist[[-1,1]]},{f}];*)


(* ::Text:: *)
(*\:0414\:0432\:0443\:043c\:0435\:0440\:043d\:044b\:0435 \:043a\:0430\:0440\:0442\:0438\:043d\:043a\:0438 - Contour*)


(* ::Input:: *)
(*PolarContourPlot[v\[Zeta]si[r,f],{r,coorlist[[1,1]],coorlist[[-1,1]]},{f}];*)
(*PolarContourPlot[\[Psi]si[r,f],{r,coorlist[[1,1]],coorlist[[-1,1]]},{f}];*)


(* ::Subsection::Closed:: *)
(*\:0414\:0440\:0443\:0433\:043e\:0435*)


(* ::Input:: *)
(*incrs=Sort[N[GetIncrements[50,2,0.01`,100]],Re[#1]>Re[#2]&];*)
(*Print[Max[Re/@incrs]];*)
(*Show[Graphics[{PointSize[0.04`],(Point[{Re[#1],Im[#1]}]&)/@incrs}],Axes->True,PlotRange->{Automatic,Automatic}]*)


(* ::Input:: *)
(*Sort[GetIncrements[300,1.,10000],Im[#1]<Im[#2]&]*)


(* ::Input:: *)
(*linc=Table[{R,GetMainIncrement[100,0,1,R,2]},{R,1,20001,100}];*)


(* ::Input:: *)
(*Timing[linc=Table[{n,(GetMainIncrement[n,0,1,1000,2])},{n,10,250,10}];]*)


(* ::Input:: *)
(*gr=PrintRange[Last/@linc];*)


(* ::Input:: *)
(*If[!NumericQ[E],Remove[E]];*)
(*cutout=6;*)
(*ltest=Last/@Drop[linc,cutout];*)
(*{lna\[Lambda],\[Lambda]}=CoefficientList[Fit[Log[-dif[ltest]],{1,x},x],x];*)
(*a=-E^lna\[Lambda]/\[Lambda];Print[{a,\[Lambda]}];*)


(* ::Input:: *)
(*ListPlot[ltest-Table[a \[ExponentialE]^(\[Lambda] x),{x,1,Length[ltest]}]]*)
